export const TUTORIAL_MMKV_ID = "TUTORIAL_MMKV_ID";

export const MAIN_TUTORIAL_KEY = "MAIN_TUTORIAL_KEY";
export const CHAT_TUTORIAL_KEY = "CHAT_TUTORIAL_KEY";
export const DIARY_TUTORIAL_KEY = "DIARY_TUTORIAL_KEY";
