on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  eas-update:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'production-update')
    uses: ./.github/workflows/eas-update.yaml

  eas-build-submit:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'production-build-submit')
    uses: ./.github/workflows/eas-build-submit.yaml
